### ISSUE TITLE
wy dis commented out 

### ISSUE THREAD

**Issue by ArthurG** [christinazhang/react-jeopardy#1]
https://github.com/christinazhang/react-jeopardy/blob/d98273ab33e58c93c1eefe516b6224bffbdd3663/src/redux/store.js#L7

**Comment by hygzhu** [comment]
no clue

**Comment by christinazhang** [comment]
I was following the example here for Redux Devtools: https://github.com/zalmoxisus/redux-devtools-extension#installation
